FROM nginx:latest

COPY ./softy.pinko-front-end /var/www/html/softy-pinko-front-end 

# copy the Nginx configuration file into the container at /etc/nginx/conf.d/default.conf
COPY ./softy-pinko-front-end.conf /etc/nginnx/conf.d/default.conf