version: '3.4'

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "5252:5252"

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "9000:9000"


